### PR TITLE
Allow checking of NFCAvailability

### PR DESCRIPTION
**Pull request by DRSchlaubi**

### CODE REVIEW

**Comment by henrysachs** [comment]
Looks good for me. I think we can merge this. Any arguments against this?

**Comment by henrysachs** [comment]
But I saw we need to update the Readme to include that MinSDK 19 is now needed instead of 18. This is kind of a breaking change.

**Comment by DRSchlaubi** [comment]
> But I saw we need to update the Readme to include that MinSDK 19 is now needed instead of 18. This is kind of a breaking change.

Yeah you're right that should be mentioned there but the plugin shouldn't have run on 18 anyways as it was using API 19 features

**Comment by henrysachs** [comment]
Okay, I'm just wondering should we update this lib to version 2.0.0 because when people are using this on an API Level 18 device it will crash. Are you sure this lib wouldnt function on an API Level 18 device?

**Comment by DRSchlaubi** [comment]
According to android Studio these calls are only available on API 19+:
https://github.com/matteocrippa/flutter-nfc-reader/blob/fc127e85a9ac5740ef368462066f6fcdbaf54486/android/src/main/kotlin/it/matteocrippa/flutternfcreader/FlutterNfcReaderPlugin.kt#L42-L46

The docs are confirming this as they say "Added in API level 19" too
https://developer.android.com/reference/android/nfc/NfcAdapter#FLAG_READER_NFC_A
https://developer.android.com/reference/android/nfc/NfcAdapter#FLAG_READER_NFC_B
https://developer.android.com/reference/android/nfc/NfcAdapter#FLAG_READER_NFC_BARCODE
https://developer.android.com/reference/android/nfc/NfcAdapter#FLAG_READER_NFC_F
https://developer.android.com/reference/android/nfc/NfcAdapter#FLAG_READER_NFC_V

EDIT: I just saw that this is checked here: https://github.com/matteocrippa/flutter-nfc-reader/blob/fc127e85a9ac5740ef368462066f6fcdbaf54486/android/src/main/kotlin/it/matteocrippa/flutternfcreader/FlutterNfcReaderPlugin.kt#L72-L74

but I think it tries to initialize `READER_FLAGS` anyways as long as it does not target 19

EDIT 2:
https://github.com/matteocrippa/flutter-nfc-reader/blob/fc127e85a9ac5740ef368462066f6fcdbaf54486/android/src/main/kotlin/it/matteocrippa/flutternfcreader/FlutterNfcReaderPlugin.kt#L23
`NfcAdapter.ReaderCallback` is API 19+ too: https://developer.android.com/reference/android/nfc/NfcAdapter.ReaderCallback.html

**Comment by henrysachs** [comment]
than we just need to discuss about the versioning here. @matteocrippa @f1re  what do you think. Is this just a 1.2.0 or a 2.0.0? I also saw that the last merge just happenend in master and not in develop.

**Comment by DRSchlaubi** [comment]
Btw what's the reason for these functions since there aren't used anywhere according to Android Studio
https://github.com/matteocrippa/flutter-nfc-reader/blob/fc127e85a9ac5740ef368462066f6fcdbaf54486/android/src/main/kotlin/it/matteocrippa/flutternfcreader/FlutterNfcReaderPlugin.kt#L123-L133
https://github.com/matteocrippa/flutter-nfc-reader/blob/fc127e85a9ac5740ef368462066f6fcdbaf54486/android/src/main/kotlin/it/matteocrippa/flutternfcreader/FlutterNfcReaderPlugin.kt#L178-L182

**Comment by henrysachs** [comment]
seems to be old unused methods. The Stop Method should be called when the method channel stop is invoked and the createNfcMessage seems to be deprecated through the Constructors used in the write method.

**Comment by alex-deutsch** [comment]
yes actually that was my mistake also, we merged the PR into master directly, i didn't realize there was a develop. How should we proceed ? So merging strategy is develop and then only for releases we merge into master  @matteocrippa  @henrysachs ?  change the PR to point to develop  @DRSchlaubi then we bring develop to latest master commit and afterwards who is doing the release including version ? @henrysachs i would suggest to go for 1.2.0, but i'm fine with 2.0.0 either..

**Comment by henrysachs** [comment]
So yeah the strategy is develop -> master  and when merged in master and we feel confident we release. About that version number I just saw that we are currently at 0.1.0 so I would like to up this to a 1.0.0 to have a „real“ release and call it a day. I think the functionality we currently have is kind of „production ready“. The real release can only be done by @matteocrippa don’t know if he can give access rights to the pub library. So yeah @DRSchlaubi it would be nice if you could point the pr against develop and @f1re if you could update the branch and do the merging because I currently have no access to a pc. 😅

PS: I just saw we all live in Germany so Deutschland muss echt ein Interesse an NFC haben :D

**Comment by alex-deutsch** [comment]
allright closing the PR then, getting develop to the right commit. Und ja sieht so aus ;-) aber @DRSchlaubi und ich arbeiten am gleichen Flutter Projekt

**Comment by alex-deutsch** [comment]
i actually just saw that @matteocrippa merged another PR into master before me, so develop was not update to date and the current state is a bit messed if we want to continue using develop in between releases. Otherwise i suggest to just use master for PR and just do releases (tags and so on) whenever we feel comfortable for a release. Actually i personally also got rid of this develop/master branches (and just use one either develop or master) in projects because it feels quite redundant to me

**Comment by henrysachs** [comment]
I use this technique in my own projects too. So for me this is fine.

**Comment by alex-deutsch** [comment]
ok i'll gonna merge it then

**Pull request merged**
